[project]
name = "turbopuffer-sdk-bench-python"
version = "0.1.0"
description = "Benchmarks for the turbopuffer Python SDK"
requires-python = ">=3.12"
dependencies = [
    "pyperf>=2.9.0",
    "numpy>=1.26.3",
    "turbopuffer[fast]>=0.1.34",
    "typing-extensions>=4.12.2",
]
