[project]
name = "turbopuffer-sdk-bench-python-async"
version = "0.1.0"
description = "Benchmarks for the turbopuffer async Python SDK"
requires-python = ">=3.12"
dependencies = [
    "pyperf>=2.9.0",
    "turbopuffer[fast]>=0.5.0",
    "typing-extensions>=4.12.2",
]
